### ISSUE TITLE
Image paths

### ISSUE THREAD

**Issue by martoio** [tvnisp/DasmotoArtsnCrafts#3]
This is a really clever to go around file path issues, I'll give you that! You should be using a local path. If you do: `../images/pattern.jpeg`, it should work.

https://www.kirupa.com/html5/all_about_file_paths.htm
https://blog.codeanalogies.com/2018/06/24/file-directories-explained-by-getting-dressed-in-the-morning/

https://github.com/tvnisp/DasmotoArtsnCrafts/blob/5d3ccde1bdbd35707311b5a44c39d064afe1eef8/resources/css/index.css#L7

**Comment by tvnisp** [comment]
I couldn’t make it work with the url. That’s why I used this github url. Thanks for the hint.
